<h1>Next</h1>

<div>
<?php 

// var_dump($this->answer);
// convert array to string 

$answer = implode("|",$this->answer);

$form = $this->form;
$form->setAttribute('action','/learn/next');
$form->prepare();

echo $this->form()->openTag($form);

$submit = $form->get('next');

$myhidden = $form->get('my-hidden');

$myhidden->setAttribute('value',$answer);

echo $this->formRow($myhidden);
echo $this->formRow($submit);

echo $this->form()->closeTag();
?>
</div>